/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PhotonicCrystal_1D;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 *
 * @author Horang
 */
public class Exp_Plot_Test extends javax.swing.JApplet {

    /**
     * Initializes the applet Exp_Plot_Test
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exp_Plot_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exp_Plot_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exp_Plot_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exp_Plot_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    Plot(slider_angle.getValue()*3.14159/180, slider_offset.getValue(), slider_nol.getValue());
                    
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slider_angle = new javax.swing.JSlider();
        panel1 = new java.awt.Panel();
        slider_offset = new javax.swing.JSlider();
        slider_nol = new javax.swing.JSlider();

        setPreferredSize(new java.awt.Dimension(800, 600));

        slider_angle.setMaximum(90);
        slider_angle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_angleStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        slider_offset.setValue(0);
        slider_offset.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_offsetStateChanged(evt);
            }
        });

        slider_nol.setMaximum(10);
        slider_nol.setValue(1);
        slider_nol.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_nolStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slider_nol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slider_angle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(slider_offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(slider_nol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slider_angleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_angleStateChanged
        // TODO add your handling code here:
        Plot(slider_angle.getValue()*3.14159/180, slider_offset.getValue(), slider_nol.getValue());
    }//GEN-LAST:event_slider_angleStateChanged

    private void slider_offsetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_offsetStateChanged
        // TODO add your handling code here:
        Plot(slider_angle.getValue()*3.14159/180, slider_offset.getValue(), slider_nol.getValue());
    }//GEN-LAST:event_slider_offsetStateChanged

    private void slider_nolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_nolStateChanged
        // TODO add your handling code here:
        
        Plot(slider_angle.getValue()*3.14159/180, slider_offset.getValue(), slider_nol.getValue());
        
        // 여기에 작성
        
    }//GEN-LAST:event_slider_nolStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel panel1;
    private javax.swing.JSlider slider_angle;
    private javax.swing.JSlider slider_nol;
    private javax.swing.JSlider slider_offset;
    // End of variables declaration//GEN-END:variables

    
    

    static List<Double> testdata(int nOfData, double maxValue) {
        List<Double> testdata = new ArrayList<>();
        Random random = new Random();
        int maxDataPoints = nOfData;
        //double maxScore = maxvalue;
                     
        for (int i = 0; i < maxDataPoints; i++) {
            //double tempnum;
            testdata.add((double) random.nextDouble() * maxValue);
        }  // Making data in here
        
        return testdata;
    }
    

    private void Plot(double angle,int yoffset,int nol) {
                    panel1.setPreferredSize(new Dimension(300,300));
                    panel1.removeAll();
                    panel1.setLayout(new java.awt.BorderLayout());
                    DrawingPanel gpanel = new DrawingPanel(angle);

                    gpanel.set_yoffset(yoffset);
                    gpanel.set_number_of_layer(nol);
                    
                    panel1.add(gpanel,BorderLayout.CENTER);
                    panel1.validate();
    }
    
    
}
